name: ramzi_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Utility
  get: ^4.6.6
  intl: ^0.20.2
  http: ^1.2.1
  dartz: ^0.10.1
  jiffy: ^6.3.1
  path: ^1.9.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3

#  timelines_plus:
  timeline_tile: ^2.0.0

  # UI & Animation
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  qr_flutter: ^4.1.0
  grouped_list: ^5.1.2
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  fluttericon: ^2.0.0

  # Firebase
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  cloud_firestore: ^5.0.2
#  flutter_local_notifications: ^17.2.1

  firebase_analytics: ^11.6.0
  # Google Services
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_sign_in: ^6.2.1

  # Local Database
  sqflite: ^2.3.3

  # Image & Scanning
  image_picker: ^1.1.2
  mobile_scanner: ^5.1.1
  flutter_otp_text_field: ^1.5.1+1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  device_preview: ^1.2.0
  responsive_builder: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900

#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Poppins-ExtraBold.ttf
#          weight: 800
#
#    - family: Inter
#      fonts:
#        - asset: assets/fonts/Inter_18pt-Regular.ttf
#        - asset: assets/fonts/Inter_18pt-Medium.ttf
#          weight: 500